"""System prompt builder — combines persona, user profile, and board state.

Assembles the full system prompt for the AI agent from:
1. SOUL.md (chess coach persona)
2. User profile (rating, goals, weaknesses, style)
3. Current board state (FEN, move history if PGN loaded)
4. Available tools summary
5. Platform ratings (auto-synced from linked accounts)
"""

import hashlib
import logging
import threading
from collections import OrderedDict
from datetime import datetime, timezone
from typing import Optional

from src.user_profile import UserProfile

logger = logging.getLogger(__name__)

# ── Prompt versioning ──────────────────────────────────────────────────
# A stable fingerprint of the coach's system-prompt inputs, stamped onto every
# logged turn and onto coach_messages so a reply can be traced back to the exact
# persona + template that produced it. Bump PROMPT_TEMPLATE_VERSION whenever the
# in-code prompt scaffolding (tool instructions, structure) changes materially;
# SOUL.md edits are picked up automatically via its mtime.
PROMPT_TEMPLATE_VERSION = "1"

_prompt_version_lock = threading.Lock()
_prompt_version_cache: Optional[str] = None
_prompt_version_mtime: Optional[float] = None


def _compute_prompt_version(soul_content: str) -> str:
    """First 10 hex chars of sha256(SOUL.md + template version constant)."""
    digest = hashlib.sha256(
        (soul_content + PROMPT_TEMPLATE_VERSION).encode("utf-8")
    ).hexdigest()
    return digest[:10]


def get_prompt_version() -> str:
    """Return the current prompt version, recomputing only on SOUL.md change.

    Reads SOUL.md via the config loader and caches the hash keyed on the file's
    mtime, so the sha256 is computed once and only recomputed when the persona
    file (or the in-code template version) changes. Fully defensive: any failure
    reading SOUL.md falls back to hashing just the template version constant so a
    caller always gets a stable, non-empty version string.
    """
    global _prompt_version_cache, _prompt_version_mtime
    try:
        from src.config import PROFILE_DIR

        soul_path = PROFILE_DIR / "SOUL.md"
        mtime = soul_path.stat().st_mtime
        with _prompt_version_lock:
            if _prompt_version_cache is not None and _prompt_version_mtime == mtime:
                return _prompt_version_cache
            version = _compute_prompt_version(soul_path.read_text())
            _prompt_version_cache = version
            _prompt_version_mtime = mtime
            return version
    except Exception:
        logger.debug("prompt version computation failed; using template-only hash", exc_info=True)
        return _compute_prompt_version("")

# Bounded LRU cache for FEN-keyed board analysis. The analysis block is a pure
# function of the FEN, so an unchanged position can reuse the previous result
# and skip the Mastra CCP HTTP call / local recompute. Only successful results
# are cached — a None/failed lookup is never stored, so a transient failure is
# retried on the next turn (preserving the existing defensive fallback).
_ANALYSIS_CACHE_MAX = 512
_analysis_cache: "OrderedDict[str, str]" = OrderedDict()
_analysis_cache_lock = threading.Lock()


def clear_analysis_cache() -> None:
    """Empty the FEN-keyed board-analysis cache (used by tests)."""
    with _analysis_cache_lock:
        _analysis_cache.clear()


def _resolve_board_analysis(fen: str) -> Optional[str]:
    """Return the board-analysis block for a FEN, with a bounded LRU cache.

    Prefers Mastra's CCP service and falls back to the local Python port on any
    failure — identical to the original inline logic. Successful results are
    cached keyed on the exact FEN string so a repeated position returns the same
    block without a second fetch/recompute. Failed lookups are never cached.
    """
    with _analysis_cache_lock:
        cached = _analysis_cache.get(fen)
        if cached is not None:
            _analysis_cache.move_to_end(fen)
            return cached

    analysis = _fetch_ccp_analysis(fen)
    if not analysis:
        from src.tools.tactical_board import build_board_analysis
        analysis = build_board_analysis(fen)

    if analysis:
        with _analysis_cache_lock:
            _analysis_cache[fen] = analysis
            _analysis_cache.move_to_end(fen)
            while len(_analysis_cache) > _ANALYSIS_CACHE_MAX:
                _analysis_cache.popitem(last=False)
    return analysis


def _fetch_ccp_analysis(fen: str) -> Optional[str]:
    """Fetch board analysis from the Mastra CCP HTTP service.

    POSTs {fen} to MASTRA_CCP_URL and returns the `<detailed_board_analysis>`
    block generated by Mastra's PositionPrompter. Fully defensive: returns None
    on any non-200 response, timeout, connection error, or malformed body so the
    caller can fall back to the local Python port.
    """
    try:
        import httpx

        from src.config import MASTRA_CCP_URL, MASTRA_CCP_TIMEOUT

        resp = httpx.post(
            MASTRA_CCP_URL, json={"fen": fen}, timeout=MASTRA_CCP_TIMEOUT
        )
        if resp.status_code != 200:
            return None
        data = resp.json()
        if data.get("valid") and data.get("board_analysis"):
            return data["board_analysis"]
        return None
    except Exception:
        logger.debug("Mastra CCP analysis fetch failed", exc_info=True)
        return None


def _fire_and_forget_sync(user_id: str) -> None:
    """Sync ratings in a background thread. Does not block prompt building."""
    try:
        from src.platform_linking import sync_ratings
        sync_ratings(user_id=user_id)
    except Exception:
        logger.debug("Background rating sync failed for %s", user_id, exc_info=True)


def maybe_sync_ratings(user_id: str) -> None:
    """Trigger a non-blocking background sync of platform ratings."""
    t = threading.Thread(target=_fire_and_forget_sync, args=(user_id,), daemon=True)
    t.start()


LOCALE_TO_LANGUAGE = {
    "ru": "Russian",
    "kz": "Kazakh",
    "en": "English",
}


def build_system_prompt(
    soul_content: str,
    user_profile: Optional[UserProfile] = None,
    board_fen: Optional[str] = None,
    move_history: Optional[list[str]] = None,
    locale: Optional[str] = None,
) -> str:
    """Build the full system prompt for the chess coaching agent.

    Args:
        soul_content: The SOUL.md persona text.
        user_profile: Optional user profile for personalization.
        board_fen: Optional current board FEN position.
        move_history: Optional list of SAN moves played so far.
        locale: Optional UI locale code (e.g. 'ru', 'kz', 'en').

    Returns:
        Complete system prompt string.
    """
    sections = []

    # Inject mandatory language directive before everything else
    if locale and locale != "en":
        language_name = LOCALE_TO_LANGUAGE.get(locale, locale)
        sections.append(
            f"CRITICAL LANGUAGE RULE: You MUST respond entirely in {language_name}. "
            f"All explanations, questions, and chess commentary must be in {language_name}. "
            "This is non-negotiable — never switch to English unless the user explicitly writes in English."
        )

    # ── Static prefix ──────────────────────────────────────────────────
    # SOUL persona and the tool-usage instructions never change turn-to-turn,
    # so they lead the prompt to form a stable Anthropic prompt-cache prefix.
    # All volatile blocks (current date, profile, board state) come AFTER so a
    # cache hit survives across turns. Order is valid for every provider.
    sections.append(soul_content.rstrip())

    # Tool instructions (static)
    sections.append(
        "## Tool Usage (MANDATORY)\n"
        "You have access to chess tools. You MUST use them — never answer "
        "game/player/opening questions from memory alone.\n\n"
        "### search_master_games\n"
        "ALWAYS call this tool when the user asks about a player's games, "
        "recent tournaments, head-to-head records, or specific game examples. "
        "Never say 'I don't have data' or 'the tournament hasn't happened yet' "
        "without searching first.\n\n"
        "Search tips:\n"
        "- Use the player's SURNAME only (e.g. player=\"Sindarov\" not \"Javohir Sindarov\")\n"
        "- For events, use the key word (e.g. event=\"Candidates\" not \"Candidates Match\")\n"
        "- Always set year_min for recent tournaments (e.g. year_min=2026)\n"
        "- If first search returns no results, retry with broader terms "
        "(drop event filter, widen year range)\n\n"
        "### Board Control — board_control (USE PROACTIVELY)\n"
        "Your PRIMARY teaching tool. The student has an interactive board — use it constantly.\n\n"
        "Actions and when to use them:\n"
        "- **set_fen**: Set a position on the board. Use whenever explaining a concept, "
        "tactic, or strategic idea. Construct clear example positions for pins, forks, "
        "skewers, discovered attacks, etc.\n"
        "- **load_pgn**: Load a full game on the board. Use when referencing master games "
        "so the student can replay the moves.\n"
        "- **draw_arrows**: Highlight key lines, threats, and tactical patterns. "
        "Use green for good moves, red for threats, blue for alternatives.\n"
        "- **highlight_squares**: Mark important squares — outposts, weak squares, "
        "targets, key central squares.\n"
        "- **set_puzzle**: Present a tactical puzzle for the student to solve.\n"
        "- **navigate**: Move forward/back through a loaded game.\n"
        "- **flip_board**: Flip the board perspective.\n"
        "- **clear_board**: Reset the board.\n\n"
        "GOLDEN RULE: If you are explaining a chess concept and the board is empty or "
        "shows an unrelated position, SET UP an example position FIRST, then explain. "
        "Never describe a position in words alone.\n\n"
        "Example — showing a pin:\n"
        "Call board_control with:\n"
        '  action_type: "set_fen"\n'
        '  fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4"\n'
        "Then call board_control again with:\n"
        '  action_type: "draw_arrows"\n'
        '  arrows: [{"from": "h5", "to": "f7", "brush": "red"}]\n\n'
        "This shows the Scholar's Mate threat with an arrow. "
        "ALWAYS call the tool — never just describe the position in text.\n\n"
        "### Lichess/Chess.com Game Loading Workflow\n"
        "When the user asks to find, load, or show a game from Lichess or Chess.com:\n"
        "1. Call lichess_game_import or chesscom_game_import with the username and max_games=1\n"
        "2. The result includes last_games with pgn field — take the PGN from there\n"
        "3. Call board_control with action_type=\"load_pgn\" and pgn=<the PGN from step 2>\n"
        "Never say you cannot load the game — always follow this 2-step workflow.\n\n"
        "### analyze_position\n"
        "Use Stockfish for position evaluation.\n\n"
        "### check_moves\n"
        "Verify any specific move you suggest that did not come from "
        "analyze_position/compare_variations output with check_moves before "
        "recommending it — never suggest an illegal move.\n\n"
        "CRITICAL: Your training data is outdated. The database has games "
        "through April 2026 including the FIDE Candidates 2026. ALWAYS search "
        "before claiming a tournament hasn't happened or a player has no games. "
        "If a search returns 0 results, try again with fewer/broader filters "
        "before giving up."
    )

    # ── Volatile suffix ────────────────────────────────────────────────
    # Everything below changes turn-to-turn (or day-to-day) and therefore
    # trails the static prefix above so it never busts the cached prefix.

    # Current date so the model knows what year it is
    now = datetime.now(timezone.utc)
    sections.append(
        f"## Current Date\nToday is {now.strftime('%B %d, %Y')}. "
        "Use this when interpreting time references in user queries."
    )

    # Fire-and-forget rating sync for linked platform accounts
    if user_profile:
        maybe_sync_ratings(user_profile.user_id)

    # User context
    if user_profile:
        context = user_profile.to_prompt_context()
        if context:
            sections.append(f"## Student Profile\n{context}")

    # Failure memory (CL Phase 1): inject the student's most recent verified
    # mistakes so the coach avoids repeating them. Flag-gated (default OFF → this
    # block is a no-op and the prompt is byte-identical) and fully fail-open.
    if user_profile:
        try:
            from src.config import COACH_MEMORY_WRITER

            if COACH_MEMORY_WRITER:
                from src.memory_writer import (
                    load_active_corrections,
                    render_corrections_block,
                )

                block = render_corrections_block(
                    load_active_corrections(user_profile.user_id, limit=3)
                )
                if block:
                    sections.append(block)
        except Exception:
            logger.debug("corrections injection failed", exc_info=True)

    # Game retrieval digest (CL Phase 1, Slice 2): inject a compact summary of the
    # student's own recently reviewed games. Flag-gated (COACH_GAME_RAG, default
    # OFF → no-op, prompt byte-identical) and fully fail-open.
    if user_profile:
        try:
            from src.config import COACH_GAME_RAG

            if COACH_GAME_RAG:
                from src.tools.game_insights import (
                    load_recent_insights,
                    render_games_block,
                )

                block = render_games_block(
                    load_recent_insights(user_profile.user_id, limit=3)
                )
                if block:
                    sections.append(block)
        except Exception:
            logger.debug("game insights injection failed", exc_info=True)

    # Coaching playbook (CL Phase 2, Slice 1): inject up to 3 relevant, engine-
    # verified coaching patterns distilled from real transcripts. Flag-gated
    # (COACH_PLAYBOOK, default OFF → no-op, prompt byte-identical), fully
    # fail-open, and served from an in-process TTL cache so it adds no per-turn
    # DB latency spike. Curation is offline; this only reads.
    try:
        from src.config import COACH_PLAYBOOK

        if COACH_PLAYBOOK:
            from src.playbook import build_turn_context, load_playbook_block

            context = build_turn_context(
                board_fen=board_fen,
                move_history=move_history,
                user_profile=user_profile,
            )
            block = load_playbook_block(context)
            if block:
                sections.append(block)
    except Exception:
        logger.debug("playbook injection failed", exc_info=True)

    # Automatic curriculum (CL Phase 2, Slice 2): inject the student's current
    # "Training focus (engine-measured)" — ≤3 themes keyed on engine-measured
    # learnability (high blunder rate near their ~50% solve frontier). Flag-gated
    # (COACH_CURRICULUM, default OFF → no-op, prompt byte-identical), fully fail-
    # open, and served from an in-process per-user TTL cache so it adds no per-
    # turn DB latency spike. The curriculum is computed OFFLINE; this only reads.
    if user_profile:
        try:
            from src.config import COACH_CURRICULUM

            if COACH_CURRICULUM:
                from src.curriculum import load_curriculum_block

                block = load_curriculum_block(user_profile.user_id)
                if block:
                    sections.append(block)
        except Exception:
            logger.debug("curriculum injection failed", exc_info=True)

    # Board context
    board_lines = []
    if board_fen:
        board_lines.append(f"Current position (FEN): {board_fen}")
        # Auto-inject structured tactical board analysis so every coach turn
        # with a FEN gets pins/hanging/semi-protected context without relying
        # on an optional tool call. Prefer Mastra's CCP service (the canonical
        # PositionPrompter fusion); fall back to the local Python port on any
        # failure. Defensive: invalid FEN or both paths failing must not crash.
        try:
            analysis = _resolve_board_analysis(board_fen)
            if analysis:
                board_lines.append(analysis)
        except Exception:
            logger.debug("Board analysis injection failed", exc_info=True)
    if move_history:
        moves_str = " ".join(
            f"{i // 2 + 1}. {move}" if i % 2 == 0 else move
            for i, move in enumerate(move_history)
        )
        board_lines.append(f"Move history: {moves_str}")

    if board_lines:
        sections.append(f"## Current Board State\n" + "\n".join(board_lines))

    return "\n\n".join(sections)


# Spoken-style adaptation layer: turns the shared SOUL persona into a live-voice
# coach. Kept as a constant so the single source of truth for the *persona* stays
# SOUL.md while the *spoken* delivery rules live here (mirrors the directives the
# live-token route used to hand-write, so voice behavior is preserved).
VOICE_STYLE_LAYER = (
    "## Speaking Style (voice mode)\n"
    "You are now speaking out loud in a live voice conversation — the same "
    "coach the player types with. Talk the way a coach sitting beside the board "
    "would:\n"
    "- Keep sentences short, natural, and conversational. NO markdown, NO bullet "
    "points, NO headings, NO long monologues — this is spoken, not written.\n"
    "- Refer to squares, pieces, threats, and simple plans out loud (e.g. "
    "\"the knight on d5\", \"the pawn on e4\").\n"
    "- Ask a short question when you're unsure what the player sees, rather than "
    "lecturing. Lead them to the idea instead of just handing over the move.\n"
    "- Never break character or say things like \"as a chess AI\"."
)

VOICE_TOOL_LAYER = (
    "## Tools (voice mode)\n"
    "You have tools. Use board_control to demonstrate ideas directly on the "
    "board — set positions, draw arrows, highlight squares, step through moves — "
    "and use the engine and database tools (analyze the position, search master "
    "games, opening and position stats) instead of guessing or inventing lines.\n"
    "CRITICAL for a live voice conversation: the moment you decide to call a "
    "tool, FIRST speak a brief spoken acknowledgment out loud (something like "
    "\"let me check that\" or \"one sec, looking now\") and THEN make the tool "
    "call. Never go silent while a tool runs — the player should always hear you "
    "respond right away.\n"
    "Before you recommend or name a specific move that did NOT come from "
    "analyze_position or compare_variations output, silently verify it with "
    "check_moves first; if it comes back illegal, pick a legal move from the "
    "returned list instead — never speak an illegal move."
)


def build_voice_prompt(
    soul_content: str,
    user_profile: Optional[UserProfile] = None,
    board_fen: Optional[str] = None,
    locale: Optional[str] = None,
    tools_available: bool = True,
) -> str:
    """Build the spoken system prompt for the Gemini Live voice coach.

    Renders from the SAME sources as the text prompt so the two modes can't
    drift: the SOUL.md persona core, then a spoken-style adaptation layer (short
    sentences, no markdown, speak-before-tool-call), the student profile, and a
    compact current-position line. Deliberately omits the heavy tactical board
    analysis the text path injects — voice minting is latency-sensitive and the
    spoken coach reads the board out loud rather than from an analysis dump.

    Args:
        soul_content: The SOUL.md persona text (single source of truth).
        user_profile: Optional profile for personalization (rating/goals/weaknesses).
        board_fen: Optional current FEN to anchor the conversation.
        locale: Optional UI locale code ('ru', 'kz', 'en').
        tools_available: Include the spoken tool-use directives (default True).

    Returns:
        Complete spoken system prompt string.
    """
    sections = []

    # Same mandatory language directive the text prompt leads with.
    if locale and locale != "en":
        language_name = LOCALE_TO_LANGUAGE.get(locale, locale)
        sections.append(
            f"CRITICAL LANGUAGE RULE: You MUST respond entirely in {language_name}. "
            f"All spoken explanations, questions, and chess commentary must be in "
            f"{language_name}. This is non-negotiable — never switch to English "
            "unless the player speaks to you in English."
        )

    # Persona core (shared with text) + spoken delivery overrides.
    sections.append(soul_content.rstrip())
    sections.append(VOICE_STYLE_LAYER)

    # Student profile — same context text chat gets (Task 2 parity).
    if user_profile:
        context = user_profile.to_prompt_context()
        if context:
            sections.append(f"## Student Profile\n{context}")

    # Compact current-position anchor (no tactical-analysis injection).
    if board_fen:
        sections.append(
            "## Current Board State\n"
            f"The current position (FEN) is: {board_fen}. Refer to it when relevant."
        )

    if tools_available:
        sections.append(VOICE_TOOL_LAYER)

    return "\n\n".join(sections)
