export const ECO_NAMES: Record<string, string> = {
  // A: Flank Openings & Queen's Pawn (without ...d5)
  "A00": "Uncommon Opening",
  "A01": "Nimzowitsch-Larsen Attack",
  "A02": "Bird's Opening",
  "A03": "Bird's Opening",
  "A04": "Réti Opening",
  "A05": "Réti Opening",
  "A06": "Réti Opening",
  "A07": "Réti: King's Indian Attack",
  "A08": "Réti: King's Indian Attack",
  "A09": "Réti Opening",
  "A10": "English Opening",
  "A11": "English: Caro-Kann Defensive System",
  "A12": "English: Caro-Kann Defensive System",
  "A13": "English Opening",
  "A14": "English: Neo-Catalan Declined",
  "A15": "English: Anglo-Indian Defense",
  "A16": "English Opening",
  "A17": "English: Hedgehog",
  "A18": "English: Mikenas-Carls Variation",
  "A19": "English: Mikenas-Carls Variation",
  "A20": "English Opening",
  "A21": "English Opening",
  "A22": "English: Bremen System",
  "A23": "English: Bremen System",
  "A24": "English: Bremen System",
  "A25": "English: Sicilian Reversed",
  "A26": "English: Closed System",
  "A27": "English: Three Knights System",
  "A28": "English: Four Knights Variation",
  "A29": "English: Four Knights Variation",
  "A30": "English: Symmetrical Variation",
  "A31": "English: Symmetrical, Benoni Formation",
  "A32": "English: Symmetrical Variation",
  "A33": "English: Symmetrical, Geller Variation",
  "A34": "English: Symmetrical Variation",
  "A35": "English: Symmetrical Variation",
  "A36": "English: Symmetrical, Botvinnik System",
  "A37": "English: Symmetrical Variation",
  "A38": "English: Symmetrical Variation",
  "A39": "English: Symmetrical, Main Line",
  "A40": "Queen's Pawn Game",
  "A41": "Queen's Pawn: Wade Defense",
  "A42": "Modern Defense: Averbakh System",
  "A43": "Old Benoni Defense",
  "A44": "Old Benoni: Czech Variation",
  "A45": "Queen's Pawn Game",
  "A46": "Queen's Pawn: Indian Defense",
  "A47": "Queen's Indian: Marienbad System",
  "A48": "London System",
  "A49": "London System",
  "A50": "Queen's Pawn Game",
  "A51": "Budapest Gambit",
  "A52": "Budapest Gambit",
  "A53": "Old Indian Defense",
  "A54": "Old Indian: Ukrainian Variation",
  "A55": "Old Indian: Main Line",
  "A56": "Benoni Defense",
  "A57": "Benko Gambit",
  "A58": "Benko Gambit: Accepted",
  "A59": "Benko Gambit: Accepted, Main Line",
  "A60": "Benoni Defense",
  "A61": "Benoni: Fianchetto Variation",
  "A62": "Benoni: Fianchetto, Hastings Variation",
  "A63": "Benoni: Fianchetto, Main Line",
  "A64": "Benoni: Fianchetto, Czerniak Variation",
  "A65": "Benoni: Taimanov Variation",
  "A66": "Benoni: Mikenas Variation",
  "A67": "Benoni: Taimanov, Flank Attack",
  "A68": "Benoni: Four Pawns Attack",
  "A69": "Benoni: Four Pawns, Main Line",
  "A70": "Benoni: Classical Variation",
  "A71": "Benoni: Classical, Averbakh-Geller",
  "A72": "Benoni: Classical, Averbakh-Geller",
  "A73": "Benoni: Classical, Main Line",
  "A74": "Benoni: Classical, Full Line",
  "A75": "Benoni: Classical, Main Line",
  "A76": "Benoni: Classical, Main Line",
  "A77": "Benoni: Classical, Main Line",
  "A78": "Benoni: Classical with ...Re8",
  "A79": "Benoni: Classical, Main Line",
  "A80": "Dutch Defense",
  "A81": "Dutch Defense",
  "A82": "Dutch: Staunton Gambit",
  "A83": "Dutch: Staunton Gambit, Main Line",
  "A84": "Dutch Defense",
  "A85": "Dutch: Queen's Knight Variation",
  "A86": "Dutch: Fianchetto Variation",
  "A87": "Dutch: Leningrad, Main Line",
  "A88": "Dutch: Leningrad, Main Line",
  "A89": "Dutch: Leningrad, Main Line",
  "A90": "Dutch Defense",
  "A91": "Dutch Defense",
  "A92": "Dutch: Stonewall Variation",
  "A93": "Dutch: Stonewall, Botvinnik Variation",
  "A94": "Dutch: Stonewall with Ba6",
  "A95": "Dutch: Stonewall, Main Line",
  "A96": "Dutch: Classical Variation",
  "A97": "Dutch: Ilyin-Zhenevsky Variation",
  "A98": "Dutch: Ilyin-Zhenevsky Variation",
  "A99": "Dutch: Ilyin-Zhenevsky, Main Line",

  // B: King's Pawn — Semi-Open (not 1...e5)
  "B00": "King's Pawn Game",
  "B01": "Scandinavian Defense",
  "B02": "Alekhine Defense",
  "B03": "Alekhine Defense: Four Pawns Attack",
  "B04": "Alekhine Defense: Modern Variation",
  "B05": "Alekhine Defense: Modern, Main Line",
  "B06": "Modern Defense",
  "B07": "Pirc Defense",
  "B08": "Pirc: Classical Variation",
  "B09": "Pirc: Austrian Attack",
  "B10": "Caro-Kann Defense",
  "B11": "Caro-Kann: Two Knights Variation",
  "B12": "Caro-Kann: Advance Variation",
  "B13": "Caro-Kann: Exchange Variation",
  "B14": "Caro-Kann: Panov-Botvinnik Attack",
  "B15": "Caro-Kann: Main Line",
  "B16": "Caro-Kann: Bronstein-Larsen Variation",
  "B17": "Caro-Kann: Steinitz Variation",
  "B18": "Caro-Kann: Classical Variation",
  "B19": "Caro-Kann: Classical, Main Line",
  "B20": "Sicilian Defense",
  "B21": "Sicilian: Smith-Morra Gambit",
  "B22": "Sicilian: Alapin Variation",
  "B23": "Sicilian: Closed Variation",
  "B24": "Sicilian: Closed, Main Line",
  "B25": "Sicilian: Closed, Main Line",
  "B26": "Sicilian: Closed, Main Line",
  "B27": "Sicilian Defense",
  "B28": "Sicilian: O'Kelly Variation",
  "B29": "Sicilian: Nimzowitsch Variation",
  "B30": "Sicilian Defense",
  "B31": "Sicilian: Rossolimo Variation",
  "B32": "Sicilian: Open, Löwenthal",
  "B33": "Sicilian: Sveshnikov Variation",
  "B34": "Sicilian: Accelerated Dragon",
  "B35": "Sicilian: Accelerated Dragon, Modern",
  "B36": "Sicilian: Maróczy Bind",
  "B37": "Sicilian: Maróczy Bind",
  "B38": "Sicilian: Maróczy Bind",
  "B39": "Sicilian: Maróczy Bind, Breyer",
  "B40": "Sicilian Defense",
  "B41": "Sicilian: Kan Variation",
  "B42": "Sicilian: Kan, Swiss Cheese",
  "B43": "Sicilian: Kan, Main Line",
  "B44": "Sicilian: Taimanov Variation",
  "B45": "Sicilian: Taimanov Variation",
  "B46": "Sicilian: Taimanov Variation",
  "B47": "Sicilian: Taimanov, Main Line",
  "B48": "Sicilian: Taimanov, Main Line",
  "B49": "Sicilian: Taimanov, Main Line",
  "B50": "Sicilian Defense",
  "B51": "Sicilian: Moscow Variation",
  "B52": "Sicilian: Canal-Sokolsky Attack",
  "B53": "Sicilian: Chekhover Variation",
  "B54": "Sicilian: Open",
  "B55": "Sicilian: Open",
  "B56": "Sicilian: Open",
  "B57": "Sicilian: Sozin Attack",
  "B58": "Sicilian: Classical Variation",
  "B59": "Sicilian: Classical, Main Line",
  "B60": "Sicilian: Richter-Rauzer",
  "B61": "Sicilian: Richter-Rauzer",
  "B62": "Sicilian: Richter-Rauzer",
  "B63": "Sicilian: Richter-Rauzer, Main Line",
  "B64": "Sicilian: Richter-Rauzer, Main Line",
  "B65": "Sicilian: Richter-Rauzer, Main Line",
  "B66": "Sicilian: Richter-Rauzer, Main Line",
  "B67": "Sicilian: Richter-Rauzer, Main Line",
  "B68": "Sicilian: Richter-Rauzer, Main Line",
  "B69": "Sicilian: Richter-Rauzer, Main Line",
  "B70": "Sicilian: Dragon Variation",
  "B71": "Sicilian: Dragon, Levenfish",
  "B72": "Sicilian: Dragon, Classical",
  "B73": "Sicilian: Dragon, Classical",
  "B74": "Sicilian: Dragon, Classical, Main Line",
  "B75": "Sicilian: Dragon, Yugoslav Attack",
  "B76": "Sicilian: Dragon, Yugoslav Attack",
  "B77": "Sicilian: Dragon, Yugoslav, Main Line",
  "B78": "Sicilian: Dragon, Yugoslav, Main Line",
  "B79": "Sicilian: Dragon, Yugoslav, Main Line",
  "B80": "Sicilian: Scheveningen Variation",
  "B81": "Sicilian: Scheveningen, Keres Attack",
  "B82": "Sicilian: Scheveningen",
  "B83": "Sicilian: Scheveningen, Classical",
  "B84": "Sicilian: Scheveningen",
  "B85": "Sicilian: Scheveningen, Classical Main",
  "B86": "Sicilian: Sozin Attack",
  "B87": "Sicilian: Sozin, Fischer Variation",
  "B88": "Sicilian: Sozin, Main Line",
  "B89": "Sicilian: Sozin, Main Line",
  "B90": "Sicilian: Najdorf Variation",
  "B91": "Sicilian: Najdorf, Zagreb Variation",
  "B92": "Sicilian: Najdorf, Opočenský",
  "B93": "Sicilian: Najdorf",
  "B94": "Sicilian: Najdorf",
  "B95": "Sicilian: Najdorf",
  "B96": "Sicilian: Najdorf",
  "B97": "Sicilian: Najdorf, Poisoned Pawn",
  "B98": "Sicilian: Najdorf",
  "B99": "Sicilian: Najdorf, Main Line",

  // C: King's Pawn — Open (1.e4 e5) & French
  "C00": "French Defense",
  "C01": "French: Exchange Variation",
  "C02": "French: Advance Variation",
  "C03": "French: Tarrasch Variation",
  "C04": "French: Tarrasch, Guimard Main",
  "C05": "French: Tarrasch, Closed",
  "C06": "French: Tarrasch, Closed, Main Line",
  "C07": "French: Tarrasch, Open",
  "C08": "French: Tarrasch, Open, Main Line",
  "C09": "French: Tarrasch, Open, Main Line",
  "C10": "French: Rubinstein Variation",
  "C11": "French: Classical Variation",
  "C12": "French: MacCutcheon Variation",
  "C13": "French: Classical",
  "C14": "French: Classical, Main Line",
  "C15": "French: Winawer Variation",
  "C16": "French: Winawer, Advance",
  "C17": "French: Winawer, Advance",
  "C18": "French: Winawer, Main Line",
  "C19": "French: Winawer, Main Line",
  "C20": "King's Pawn Game",
  "C21": "Center Game",
  "C22": "Center Game",
  "C23": "Bishop's Opening",
  "C24": "Bishop's Opening",
  "C25": "Vienna Game",
  "C26": "Vienna Game",
  "C27": "Vienna: Frankenstein-Dracula",
  "C28": "Vienna Game",
  "C29": "Vienna Gambit",
  "C30": "King's Gambit",
  "C31": "King's Gambit: Falkbeer Countergambit",
  "C32": "King's Gambit: Falkbeer Countergambit",
  "C33": "King's Gambit Accepted",
  "C34": "King's Gambit Accepted",
  "C35": "King's Gambit Accepted: Cunningham",
  "C36": "King's Gambit Accepted: Abbazia Defense",
  "C37": "King's Gambit Accepted: Muzio Gambit",
  "C38": "King's Gambit Accepted: Hanstein Gambit",
  "C39": "King's Gambit Accepted: Kieseritzky Gambit",
  "C40": "King's Pawn Game",
  "C41": "Philidor Defense",
  "C42": "Petrov Defense",
  "C43": "Petrov: Stafford Gambit",
  "C44": "King's Pawn Game",
  "C45": "Scotch Game",
  "C46": "Three Knights Game",
  "C47": "Four Knights Game",
  "C48": "Four Knights: Spanish Variation",
  "C49": "Four Knights: Double Ruy Lopez",
  "C50": "Italian Game",
  "C51": "Evans Gambit",
  "C52": "Evans Gambit",
  "C53": "Italian: Giuoco Piano",
  "C54": "Italian: Giuoco Piano, Main Line",
  "C55": "Two Knights Defense",
  "C56": "Two Knights: Traxler Counterattack",
  "C57": "Two Knights: Fried Liver Attack",
  "C58": "Two Knights Defense",
  "C59": "Two Knights Defense, Main Line",
  "C60": "Ruy Lopez",
  "C61": "Ruy Lopez: Bird's Defense",
  "C62": "Ruy Lopez: Old Steinitz Defense",
  "C63": "Ruy Lopez: Schliemann Defense",
  "C64": "Ruy Lopez: Classical Defense",
  "C65": "Ruy Lopez: Berlin Defense",
  "C66": "Ruy Lopez: Berlin Defense, Main Line",
  "C67": "Ruy Lopez: Berlin, Rio de Janeiro",
  "C68": "Ruy Lopez: Exchange Variation",
  "C69": "Ruy Lopez: Exchange, Main Line",
  "C70": "Ruy Lopez: Morphy Defense",
  "C71": "Ruy Lopez: Modern Steinitz Defense",
  "C72": "Ruy Lopez: Modern Steinitz Defense",
  "C73": "Ruy Lopez: Modern Steinitz Defense",
  "C74": "Ruy Lopez: Modern Steinitz Defense",
  "C75": "Ruy Lopez: Modern Steinitz Defense",
  "C76": "Ruy Lopez: Modern Steinitz, Fianchetto",
  "C77": "Ruy Lopez: Morphy Defense",
  "C78": "Ruy Lopez: Arkhangelsk Variation",
  "C79": "Ruy Lopez: Steinitz Deferred",
  "C80": "Ruy Lopez: Open Variation",
  "C81": "Ruy Lopez: Open, Howell Attack",
  "C82": "Ruy Lopez: Open, Italian Variation",
  "C83": "Ruy Lopez: Open, Classical",
  "C84": "Ruy Lopez: Closed Variation",
  "C85": "Ruy Lopez: Closed, Exchange Variation",
  "C86": "Ruy Lopez: Worrall Attack",
  "C87": "Ruy Lopez: Closed, Averbach",
  "C88": "Ruy Lopez: Closed",
  "C89": "Ruy Lopez: Marshall Attack",
  "C90": "Ruy Lopez: Closed",
  "C91": "Ruy Lopez: Closed, Bogoljubov",
  "C92": "Ruy Lopez: Closed, Zaitsev System",
  "C93": "Ruy Lopez: Closed, Smyslov Defense",
  "C94": "Ruy Lopez: Closed, Breyer Defense",
  "C95": "Ruy Lopez: Closed, Breyer, Main Line",
  "C96": "Ruy Lopez: Closed, Chigorin Defense",
  "C97": "Ruy Lopez: Closed, Chigorin, Main Line",
  "C98": "Ruy Lopez: Closed, Chigorin, Main Line",
  "C99": "Ruy Lopez: Closed, Chigorin, Main Line",

  // D: Queen's Pawn with ...d5
  "D00": "Queen's Pawn Game",
  "D01": "Richter-Veresov Attack",
  "D02": "Queen's Pawn: London System",
  "D03": "Torre Attack",
  "D04": "Queen's Pawn Game",
  "D05": "Queen's Pawn: Colle System",
  "D06": "Queen's Gambit",
  "D07": "Queen's Gambit: Chigorin Defense",
  "D08": "Queen's Gambit: Albin Countergambit",
  "D09": "Queen's Gambit: Albin Countergambit",
  "D10": "Queen's Gambit: Slav Defense",
  "D11": "Queen's Gambit: Slav Defense",
  "D12": "Queen's Gambit: Slav, Quiet Variation",
  "D13": "Queen's Gambit: Slav, Exchange Variation",
  "D14": "Queen's Gambit: Slav, Exchange, Main Line",
  "D15": "Queen's Gambit: Slav Defense",
  "D16": "Queen's Gambit: Slav, Alapin",
  "D17": "Queen's Gambit: Slav, Czech Defense",
  "D18": "Queen's Gambit: Slav, Dutch Variation",
  "D19": "Queen's Gambit: Slav, Dutch, Main Line",
  "D20": "Queen's Gambit Accepted",
  "D21": "Queen's Gambit Accepted",
  "D22": "Queen's Gambit Accepted",
  "D23": "Queen's Gambit Accepted",
  "D24": "Queen's Gambit Accepted",
  "D25": "Queen's Gambit Accepted",
  "D26": "Queen's Gambit Accepted: Classical",
  "D27": "Queen's Gambit Accepted: Classical, Main",
  "D28": "Queen's Gambit Accepted: Classical",
  "D29": "Queen's Gambit Accepted: Classical, Main",
  "D30": "Queen's Gambit Declined",
  "D31": "Queen's Gambit Declined",
  "D32": "Queen's Gambit Declined: Tarrasch Defense",
  "D33": "Queen's Gambit Declined: Tarrasch",
  "D34": "Queen's Gambit Declined: Tarrasch, Main",
  "D35": "Queen's Gambit Declined: Exchange Variation",
  "D36": "Queen's Gambit Declined: Exchange, Main",
  "D37": "Queen's Gambit Declined",
  "D38": "Queen's Gambit Declined: Ragozin Defense",
  "D39": "Queen's Gambit Declined: Ragozin, Main",
  "D40": "Queen's Gambit Declined: Semi-Tarrasch",
  "D41": "Queen's Gambit Declined: Semi-Tarrasch",
  "D42": "Queen's Gambit Declined: Semi-Tarrasch, Main",
  "D43": "Queen's Gambit Declined: Semi-Slav",
  "D44": "Queen's Gambit Declined: Semi-Slav, Botvinnik",
  "D45": "Queen's Gambit Declined: Semi-Slav",
  "D46": "Queen's Gambit Declined: Semi-Slav, Main",
  "D47": "Queen's Gambit Declined: Semi-Slav, Meran",
  "D48": "Queen's Gambit Declined: Semi-Slav, Meran",
  "D49": "Queen's Gambit Declined: Semi-Slav, Meran Main",
  "D50": "Queen's Gambit Declined",
  "D51": "Queen's Gambit Declined: Cambridge Springs",
  "D52": "Queen's Gambit Declined",
  "D53": "Queen's Gambit Declined",
  "D54": "Queen's Gambit Declined: Anti-Neo-Orthodox",
  "D55": "Queen's Gambit Declined",
  "D56": "Queen's Gambit Declined: Lasker Defense",
  "D57": "Queen's Gambit Declined: Lasker Defense, Main",
  "D58": "Queen's Gambit Declined: Tartakower Variation",
  "D59": "Queen's Gambit Declined: Tartakower, Main",
  "D60": "Queen's Gambit Declined: Orthodox Defense",
  "D61": "Queen's Gambit Declined: Orthodox",
  "D62": "Queen's Gambit Declined: Orthodox",
  "D63": "Queen's Gambit Declined: Orthodox, Main",
  "D64": "Queen's Gambit Declined: Orthodox, Rubinstein",
  "D65": "Queen's Gambit Declined: Orthodox, Rubinstein",
  "D66": "Queen's Gambit Declined: Orthodox, Main",
  "D67": "Queen's Gambit Declined: Orthodox, Main",
  "D68": "Queen's Gambit Declined: Orthodox, Classical",
  "D69": "Queen's Gambit Declined: Orthodox, Classical",
  "D70": "Grünfeld Defense",
  "D71": "Grünfeld: Hungarian Variation",
  "D72": "Grünfeld: Hungarian Variation",
  "D73": "Grünfeld: Brinckmann Attack",
  "D74": "Grünfeld: Brinckmann, Main Line",
  "D75": "Grünfeld: Makogonov Variation",
  "D76": "Grünfeld: Russian Variation",
  "D77": "Grünfeld: Fianchetto Variation",
  "D78": "Grünfeld: Fianchetto, Main Line",
  "D79": "Grünfeld: Fianchetto, Main Line",
  "D80": "Grünfeld Defense",
  "D81": "Grünfeld: Russian, Smyslov",
  "D82": "Grünfeld: Bf4 Variation",
  "D83": "Grünfeld: Bf4, Grünfeld Gambit",
  "D84": "Grünfeld: Bf4 Variation",
  "D85": "Grünfeld: Exchange Variation",
  "D86": "Grünfeld: Exchange, Classical",
  "D87": "Grünfeld: Exchange, Spassky Variation",
  "D88": "Grünfeld: Exchange, Spassky, Main",
  "D89": "Grünfeld: Exchange, Spassky, Main",
  "D90": "Grünfeld Defense",
  "D91": "Grünfeld: Three Knights Variation",
  "D92": "Grünfeld: Hungarian Variation",
  "D93": "Grünfeld: Bf4 Variation",
  "D94": "Grünfeld: Smyslov Variation",
  "D95": "Grünfeld: Smyslov, Main Line",
  "D96": "Grünfeld: Russian Variation",
  "D97": "Grünfeld: Russian, Szabo Variation",
  "D98": "Grünfeld: Russian, Smyslov Variation",
  "D99": "Grünfeld: Russian, Smyslov, Main Line",

  // E: Indian Defenses
  "E00": "Queen's Pawn: Catalan Opening",
  "E01": "Catalan Opening",
  "E02": "Catalan: Open Variation",
  "E03": "Catalan: Open, Alekhine Variation",
  "E04": "Catalan: Open Variation",
  "E05": "Catalan: Open, Classical Line",
  "E06": "Catalan: Closed Variation",
  "E07": "Catalan: Closed Variation",
  "E08": "Catalan: Closed, Main Line",
  "E09": "Catalan: Closed, Main Line",
  "E10": "Queen's Pawn: Anti-Nimzo-Indian",
  "E11": "Bogo-Indian Defense",
  "E12": "Queen's Indian Defense",
  "E13": "Queen's Indian: Main Line",
  "E14": "Queen's Indian Defense",
  "E15": "Queen's Indian: Fianchetto Variation",
  "E16": "Queen's Indian: Capablanca Variation",
  "E17": "Queen's Indian: Fianchetto, Main Line",
  "E18": "Queen's Indian: Fianchetto, Main Line",
  "E19": "Queen's Indian: Fianchetto, Main Line",
  "E20": "Nimzo-Indian Defense",
  "E21": "Nimzo-Indian: Three Knights Variation",
  "E22": "Nimzo-Indian: Spielmann Variation",
  "E23": "Nimzo-Indian: Spielmann, Main Line",
  "E24": "Nimzo-Indian: Sämisch Variation",
  "E25": "Nimzo-Indian: Sämisch, Keres",
  "E26": "Nimzo-Indian: Sämisch, Main Line",
  "E27": "Nimzo-Indian: Sämisch, Main Line",
  "E28": "Nimzo-Indian: Sämisch, Main Line",
  "E29": "Nimzo-Indian: Sämisch, Main Line",
  "E30": "Nimzo-Indian: Leningrad Variation",
  "E31": "Nimzo-Indian: Leningrad, Main Line",
  "E32": "Nimzo-Indian: Classical Variation",
  "E33": "Nimzo-Indian: Classical, Milner-Barry",
  "E34": "Nimzo-Indian: Classical, Noa",
  "E35": "Nimzo-Indian: Classical, Noa",
  "E36": "Nimzo-Indian: Classical, Noa",
  "E37": "Nimzo-Indian: Classical, Main Line",
  "E38": "Nimzo-Indian: Classical, Main Line",
  "E39": "Nimzo-Indian: Classical, Pirc Variation",
  "E40": "Nimzo-Indian: Rubinstein Variation",
  "E41": "Nimzo-Indian: Hübner Variation",
  "E42": "Nimzo-Indian: Rubinstein, Bernstein",
  "E43": "Nimzo-Indian: Fischer Variation",
  "E44": "Nimzo-Indian: Fischer Variation",
  "E45": "Nimzo-Indian: Rubinstein, Main Line",
  "E46": "Nimzo-Indian: Reshevsky Variation",
  "E47": "Nimzo-Indian: Rubinstein, Main Line",
  "E48": "Nimzo-Indian: Rubinstein, Main Line",
  "E49": "Nimzo-Indian: Rubinstein, Botvinnik",
  "E50": "Nimzo-Indian: Main Line",
  "E51": "Nimzo-Indian: Ragozin Variation",
  "E52": "Nimzo-Indian: Main Line",
  "E53": "Nimzo-Indian: Main Line",
  "E54": "Nimzo-Indian: Main Line, Karpov",
  "E55": "Nimzo-Indian: Main Line",
  "E56": "Nimzo-Indian: Main Line",
  "E57": "Nimzo-Indian: Main Line",
  "E58": "Nimzo-Indian: Main Line, Karpov",
  "E59": "Nimzo-Indian: Main Line, Karpov",
  "E60": "King's Indian Defense",
  "E61": "King's Indian Defense",
  "E62": "King's Indian: Fianchetto Variation",
  "E63": "King's Indian: Fianchetto, Panno",
  "E64": "King's Indian: Fianchetto Variation",
  "E65": "King's Indian: Fianchetto, Yugoslav",
  "E66": "King's Indian: Fianchetto, Yugoslav",
  "E67": "King's Indian: Fianchetto, Classical",
  "E68": "King's Indian: Fianchetto, Classical",
  "E69": "King's Indian: Fianchetto, Classical Main",
  "E70": "King's Indian: Accelerated Averbakh",
  "E71": "King's Indian: Makogonov Variation",
  "E72": "King's Indian Defense",
  "E73": "King's Indian: Averbakh Variation",
  "E74": "King's Indian: Averbakh, Main Line",
  "E75": "King's Indian: Averbakh, Main Line",
  "E76": "King's Indian: Four Pawns Attack",
  "E77": "King's Indian: Four Pawns, Main Line",
  "E78": "King's Indian: Four Pawns, Main Line",
  "E79": "King's Indian: Four Pawns, Main Line",
  "E80": "King's Indian: Sämisch Variation",
  "E81": "King's Indian: Sämisch",
  "E82": "King's Indian: Sämisch, Fianchetto",
  "E83": "King's Indian: Sämisch, Panno",
  "E84": "King's Indian: Sämisch, Panno Main",
  "E85": "King's Indian: Sämisch, Orthodox",
  "E86": "King's Indian: Sämisch, Orthodox, Main",
  "E87": "King's Indian: Sämisch, Orthodox",
  "E88": "King's Indian: Sämisch, Orthodox, Main",
  "E89": "King's Indian: Sämisch, Orthodox, Main",
  "E90": "King's Indian: Classical Variation",
  "E91": "King's Indian: Classical",
  "E92": "King's Indian: Classical",
  "E93": "King's Indian: Petrosian Variation",
  "E94": "King's Indian: Classical, Main Line",
  "E95": "King's Indian: Classical, Main Line",
  "E96": "King's Indian: Classical, Main Line",
  "E97": "King's Indian: Mar del Plata",
  "E98": "King's Indian: Mar del Plata, Main Line",
  "E99": "King's Indian: Mar del Plata, Main Line",
};

export function getOpeningName(eco: string): string {
  if (!eco) return "Unknown Opening";
  // Try exact match first
  if (ECO_NAMES[eco]) return ECO_NAMES[eco];
  // Try prefix match (e.g., B23 → try B20 range)
  const prefix = eco.substring(0, 1);
  for (let i = parseInt(eco.substring(1)); i >= 0; i--) {
    const key = prefix + String(i).padStart(2, '0');
    if (ECO_NAMES[key]) return ECO_NAMES[key];
  }
  return "Unknown Opening";
}
