/**
 * Tug of War (Milestone 1) puzzle data set.
 *
 * GENERATED by scripts/gen-tug-puzzles.mjs — do not edit by hand; re-run the
 * generator instead. Every position is a legal white-to-move checkmate that was
 * verified with chess.js at generation time and is re-verified by
 * __tests__/puzzles.test.ts. Deliberately easy (K+Q / K+R vs K) so beginners at
 * the Pawn/Knight rating band can solve them.
 */
import type { TugPuzzle } from './types';

export const TUG_PUZZLES: TugPuzzle[] = [
  {
    "id": "tug-q1-001",
    "fen": "k7/7Q/K7/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7a7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-002",
    "fen": "7k/Q7/7K/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7h7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-003",
    "fen": "8/8/8/8/8/K7/7Q/k7 w - - 0 1",
    "moves": [
      "h2a2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-004",
    "fen": "8/8/8/8/8/7K/Q7/7k w - - 0 1",
    "moves": [
      "a2h2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-005",
    "fen": "6Q1/8/8/8/8/8/8/5K1k w - - 0 1",
    "moves": [
      "g8g1"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-006",
    "fen": "k1K5/8/8/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b8"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-007",
    "fen": "5K1k/8/8/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g8"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-008",
    "fen": "1Q6/8/8/8/8/8/8/k1K5 w - - 0 1",
    "moves": [
      "b8b1"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-009",
    "fen": "1k6/7Q/1K6/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7b7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-010",
    "fen": "6k1/Q7/6K1/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7g7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-011",
    "fen": "8/8/8/8/8/1K6/7Q/1k6 w - - 0 1",
    "moves": [
      "h2b2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-012",
    "fen": "8/8/8/8/8/6K1/Q7/6k1 w - - 0 1",
    "moves": [
      "a2g2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-013",
    "fen": "6Q1/8/8/8/8/8/5K1k/8 w - - 0 1",
    "moves": [
      "g8g2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-014",
    "fen": "8/k1K5/8/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-015",
    "fen": "8/5K1k/8/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-016",
    "fen": "1Q6/8/8/8/8/8/k1K5/8 w - - 0 1",
    "moves": [
      "b8b2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-017",
    "fen": "2k5/7Q/2K5/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7c7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-018",
    "fen": "5k2/Q7/5K2/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7f7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-019",
    "fen": "8/8/8/8/8/2K5/7Q/2k5 w - - 0 1",
    "moves": [
      "h2c2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-020",
    "fen": "8/8/8/8/8/5K2/Q7/5k2 w - - 0 1",
    "moves": [
      "a2f2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-021",
    "fen": "6Q1/8/8/8/8/5K1k/8/8 w - - 0 1",
    "moves": [
      "g8g3"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-022",
    "fen": "8/8/k1K5/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b6"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-023",
    "fen": "8/8/5K1k/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g6"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-024",
    "fen": "1Q6/8/8/8/8/k1K5/8/8 w - - 0 1",
    "moves": [
      "b8b3"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-025",
    "fen": "3k4/7Q/3K4/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7d7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-026",
    "fen": "4k3/Q7/4K3/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7e7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-r1-027",
    "fen": "k7/8/K7/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-028",
    "fen": "7k/8/7K/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-029",
    "fen": "7R/8/8/8/8/K7/8/k7 w - - 0 1",
    "moves": [
      "h8h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-030",
    "fen": "R7/8/8/8/8/7K/8/7k w - - 0 1",
    "moves": [
      "a8a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-031",
    "fen": "R7/8/8/8/8/8/8/5K1k w - - 0 1",
    "moves": [
      "a8h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-032",
    "fen": "k1K5/8/8/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-033",
    "fen": "5K1k/8/8/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-034",
    "fen": "7R/8/8/8/8/8/8/k1K5 w - - 0 1",
    "moves": [
      "h8a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-035",
    "fen": "1k6/8/1K6/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-036",
    "fen": "6k1/8/6K1/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-037",
    "fen": "7R/8/8/8/8/1K6/8/1k6 w - - 0 1",
    "moves": [
      "h8h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-038",
    "fen": "R7/8/8/8/8/6K1/8/6k1 w - - 0 1",
    "moves": [
      "a8a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-039",
    "fen": "R7/8/8/8/8/8/5K1k/8 w - - 0 1",
    "moves": [
      "a8h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-040",
    "fen": "8/k1K5/8/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-m2-041",
    "fen": "k7/8/8/K7/8/8/8/Q7 w - - 0 1",
    "moves": [
      "a5b6",
      "a8b8",
      "a1h8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-042",
    "fen": "7k/8/8/7K/8/8/8/7Q w - - 0 1",
    "moves": [
      "h5g6",
      "h8g8",
      "h1a8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-043",
    "fen": "Q7/8/8/8/K7/8/8/k7 w - - 0 1",
    "moves": [
      "a4b3",
      "a1b1",
      "a8h1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-044",
    "fen": "7Q/8/8/8/7K/8/8/7k w - - 0 1",
    "moves": [
      "h4g3",
      "h1g1",
      "h8a1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-045",
    "fen": "8/8/8/8/8/8/8/Q3K2k w - - 0 1",
    "moves": [
      "e1f2",
      "h1h2",
      "a1h8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-046",
    "fen": "k2K3Q/8/8/8/8/8/8/8 w - - 0 1",
    "moves": [
      "d8c7",
      "a8a7",
      "h8a1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-047",
    "fen": "Q3K2k/8/8/8/8/8/8/8 w - - 0 1",
    "moves": [
      "e8f7",
      "h8h7",
      "a8h1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-048",
    "fen": "8/8/8/8/8/8/8/k2K3Q w - - 0 1",
    "moves": [
      "d1c2",
      "a1a2",
      "h1a8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  }
];
