/**
 * Tug of War (Milestone 1) puzzle data set.
 *
 * GENERATED by scripts/gen-tug-puzzles.mjs — do not edit by hand; re-run the
 * generator instead. Every position is a legal white-to-move puzzle whose
 * solution line was verified with chess.js at generation time and is re-verified by
 * __tests__/puzzles.test.ts. Deliberately easy (K+Q / K+R vs K mates plus short
 * fork / pin / skewer tactics) so beginners at the Pawn–Rook rating bands can
 * solve them, and so the offline fallback can honor a theme filter in every band.
 */
import type { TugPuzzle } from './types';

export const TUG_PUZZLES: TugPuzzle[] = [
  {
    "id": "tug-q1-001",
    "fen": "k7/7Q/K7/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7a7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-002",
    "fen": "7k/Q7/7K/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7h7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-003",
    "fen": "8/8/8/8/8/K7/7Q/k7 w - - 0 1",
    "moves": [
      "h2a2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-004",
    "fen": "8/8/8/8/8/7K/Q7/7k w - - 0 1",
    "moves": [
      "a2h2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-005",
    "fen": "6Q1/8/8/8/8/8/8/5K1k w - - 0 1",
    "moves": [
      "g8g1"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-006",
    "fen": "k1K5/8/8/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b8"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-007",
    "fen": "5K1k/8/8/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g8"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-008",
    "fen": "1Q6/8/8/8/8/8/8/k1K5 w - - 0 1",
    "moves": [
      "b8b1"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-009",
    "fen": "1k6/7Q/1K6/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7b7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-010",
    "fen": "6k1/Q7/6K1/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7g7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-011",
    "fen": "8/8/8/8/8/1K6/7Q/1k6 w - - 0 1",
    "moves": [
      "h2b2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-012",
    "fen": "8/8/8/8/8/6K1/Q7/6k1 w - - 0 1",
    "moves": [
      "a2g2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-013",
    "fen": "6Q1/8/8/8/8/8/5K1k/8 w - - 0 1",
    "moves": [
      "g8g2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-014",
    "fen": "8/k1K5/8/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-015",
    "fen": "8/5K1k/8/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-016",
    "fen": "1Q6/8/8/8/8/8/k1K5/8 w - - 0 1",
    "moves": [
      "b8b2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-017",
    "fen": "2k5/7Q/2K5/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7c7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-018",
    "fen": "5k2/Q7/5K2/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7f7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-019",
    "fen": "8/8/8/8/8/2K5/7Q/2k5 w - - 0 1",
    "moves": [
      "h2c2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-020",
    "fen": "8/8/8/8/8/5K2/Q7/5k2 w - - 0 1",
    "moves": [
      "a2f2"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-021",
    "fen": "6Q1/8/8/8/8/5K1k/8/8 w - - 0 1",
    "moves": [
      "g8g3"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-022",
    "fen": "8/8/k1K5/8/8/8/8/1Q6 w - - 0 1",
    "moves": [
      "b1b6"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-023",
    "fen": "8/8/5K1k/8/8/8/8/6Q1 w - - 0 1",
    "moves": [
      "g1g6"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-024",
    "fen": "1Q6/8/8/8/8/k1K5/8/8 w - - 0 1",
    "moves": [
      "b8b3"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-025",
    "fen": "3k4/7Q/3K4/8/8/8/8/8 w - - 0 1",
    "moves": [
      "h7d7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-q1-026",
    "fen": "4k3/Q7/4K3/8/8/8/8/8 w - - 0 1",
    "moves": [
      "a7e7"
    ],
    "rating": 500,
    "themes": [
      "mateIn1",
      "queenMate"
    ]
  },
  {
    "id": "tug-r1-027",
    "fen": "k7/8/K7/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-028",
    "fen": "7k/8/7K/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-029",
    "fen": "7R/8/8/8/8/K7/8/k7 w - - 0 1",
    "moves": [
      "h8h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-030",
    "fen": "R7/8/8/8/8/7K/8/7k w - - 0 1",
    "moves": [
      "a8a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-031",
    "fen": "R7/8/8/8/8/8/8/5K1k w - - 0 1",
    "moves": [
      "a8h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-032",
    "fen": "k1K5/8/8/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-033",
    "fen": "5K1k/8/8/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-034",
    "fen": "7R/8/8/8/8/8/8/k1K5 w - - 0 1",
    "moves": [
      "h8a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-035",
    "fen": "1k6/8/1K6/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-036",
    "fen": "6k1/8/6K1/8/8/8/8/R7 w - - 0 1",
    "moves": [
      "a1a8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-037",
    "fen": "7R/8/8/8/8/1K6/8/1k6 w - - 0 1",
    "moves": [
      "h8h1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-038",
    "fen": "R7/8/8/8/8/6K1/8/6k1 w - - 0 1",
    "moves": [
      "a8a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-039",
    "fen": "R7/8/8/8/8/8/5K1k/8 w - - 0 1",
    "moves": [
      "a8h8"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-r1-040",
    "fen": "8/k1K5/8/8/8/8/8/7R w - - 0 1",
    "moves": [
      "h1a1"
    ],
    "rating": 650,
    "themes": [
      "mateIn1",
      "rookMate"
    ]
  },
  {
    "id": "tug-m2-041",
    "fen": "k7/8/8/K7/8/8/8/Q7 w - - 0 1",
    "moves": [
      "a5b6",
      "a8b8",
      "a1h8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-042",
    "fen": "7k/8/8/7K/8/8/8/7Q w - - 0 1",
    "moves": [
      "h5g6",
      "h8g8",
      "h1a8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-043",
    "fen": "Q7/8/8/8/K7/8/8/k7 w - - 0 1",
    "moves": [
      "a4b3",
      "a1b1",
      "a8h1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-044",
    "fen": "7Q/8/8/8/7K/8/8/7k w - - 0 1",
    "moves": [
      "h4g3",
      "h1g1",
      "h8a1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-045",
    "fen": "8/8/8/8/8/8/8/Q3K2k w - - 0 1",
    "moves": [
      "e1f2",
      "h1h2",
      "a1h8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-046",
    "fen": "k2K3Q/8/8/8/8/8/8/8 w - - 0 1",
    "moves": [
      "d8c7",
      "a8a7",
      "h8a1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-047",
    "fen": "Q3K2k/8/8/8/8/8/8/8 w - - 0 1",
    "moves": [
      "e8f7",
      "h8h7",
      "a8h1"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-m2-048",
    "fen": "8/8/8/8/8/8/8/k2K3Q w - - 0 1",
    "moves": [
      "d1c2",
      "a1a2",
      "h1a8"
    ],
    "rating": 900,
    "themes": [
      "mateIn2",
      "queenMate"
    ]
  },
  {
    "id": "tug-fork-p-049",
    "fen": "2r3k1/8/8/3N4/8/8/8/6K1 w - - 0 1",
    "moves": [
      "d5e7",
      "g8h8",
      "e7c8"
    ],
    "rating": 700,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-k-050",
    "fen": "1k3r2/8/8/4N3/8/8/8/1K6 w - - 0 1",
    "moves": [
      "e5d7",
      "b8a8",
      "d7f8"
    ],
    "rating": 1000,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-r-051",
    "fen": "6K1/8/8/8/3N4/8/8/2r3k1 w - - 0 1",
    "moves": [
      "d4e2",
      "g1h1",
      "e2c1"
    ],
    "rating": 1300,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-p-052",
    "fen": "1K6/8/8/8/4N3/8/8/1k3r2 w - - 0 1",
    "moves": [
      "e4d2",
      "b1a1",
      "d2f1"
    ],
    "rating": 700,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-k-053",
    "fen": "8/K6k/8/8/4N3/7r/8/8 w - - 0 1",
    "moves": [
      "e4g5",
      "h7h8",
      "g5h3"
    ],
    "rating": 1000,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-r-054",
    "fen": "8/8/r7/3N4/8/8/k6K/8 w - - 0 1",
    "moves": [
      "d5b4",
      "a2a1",
      "b4a6"
    ],
    "rating": 1300,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-p-055",
    "fen": "8/8/7r/4N3/8/8/K6k/8 w - - 0 1",
    "moves": [
      "e5g4",
      "h2h1",
      "g4h6"
    ],
    "rating": 700,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-fork-k-056",
    "fen": "8/k6K/8/8/3N4/r7/8/8 w - - 0 1",
    "moves": [
      "d4b5",
      "a7a8",
      "b5a3"
    ],
    "rating": 1000,
    "themes": [
      "fork"
    ]
  },
  {
    "id": "tug-pin-p-057",
    "fen": "k7/8/8/q7/8/8/8/R3B1K1 w - - 0 1",
    "moves": [
      "e1a5"
    ],
    "rating": 700,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-k-058",
    "fen": "7k/8/8/7q/8/8/8/1K1B3R w - - 0 1",
    "moves": [
      "d1h5"
    ],
    "rating": 1000,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-r-059",
    "fen": "R3B1K1/8/8/8/q7/8/8/k7 w - - 0 1",
    "moves": [
      "e8a4"
    ],
    "rating": 1300,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-p-060",
    "fen": "1K1B3R/8/8/8/7q/8/8/7k w - - 0 1",
    "moves": [
      "d8h4"
    ],
    "rating": 700,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-k-061",
    "fen": "8/K7/8/B7/8/8/8/R3q2k w - - 0 1",
    "moves": [
      "a5e1"
    ],
    "rating": 1000,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-r-062",
    "fen": "k2q3R/8/8/8/7B/8/7K/8 w - - 0 1",
    "moves": [
      "h4d8"
    ],
    "rating": 1300,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-p-063",
    "fen": "R3q2k/8/8/8/B7/8/K7/8 w - - 0 1",
    "moves": [
      "a4e8"
    ],
    "rating": 700,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-pin-k-064",
    "fen": "8/7K/8/7B/8/8/8/k2q3R w - - 0 1",
    "moves": [
      "h5d1"
    ],
    "rating": 1000,
    "themes": [
      "pin"
    ]
  },
  {
    "id": "tug-skewer-p-065",
    "fen": "qk6/8/8/8/8/8/8/4R1K1 w - - 0 1",
    "moves": [
      "e1e8",
      "b8b7",
      "e8a8"
    ],
    "rating": 700,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-k-066",
    "fen": "6kq/8/8/8/8/8/8/1K1R4 w - - 0 1",
    "moves": [
      "d1d8",
      "g8g7",
      "d8h8"
    ],
    "rating": 1000,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-r-067",
    "fen": "4R1K1/8/8/8/8/8/8/qk6 w - - 0 1",
    "moves": [
      "e8e1",
      "b1b2",
      "e1a1"
    ],
    "rating": 1300,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-p-068",
    "fen": "1K1R4/8/8/8/8/8/8/6kq w - - 0 1",
    "moves": [
      "d8d1",
      "g1g2",
      "d1h1"
    ],
    "rating": 700,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-k-069",
    "fen": "8/K7/8/R7/8/8/7k/7q w - - 0 1",
    "moves": [
      "a5h5",
      "h2g2",
      "h5h1"
    ],
    "rating": 1000,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-r-070",
    "fen": "q7/k7/8/8/7R/8/7K/8 w - - 0 1",
    "moves": [
      "h4a4",
      "a7b7",
      "a4a8"
    ],
    "rating": 1300,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-p-071",
    "fen": "7q/7k/8/8/R7/8/K7/8 w - - 0 1",
    "moves": [
      "a4h4",
      "h7g7",
      "h4h8"
    ],
    "rating": 700,
    "themes": [
      "skewer"
    ]
  },
  {
    "id": "tug-skewer-k-072",
    "fen": "8/7K/8/7R/8/8/k7/q7 w - - 0 1",
    "moves": [
      "h5a5",
      "a2b2",
      "a5a1"
    ],
    "rating": 1000,
    "themes": [
      "skewer"
    ]
  }
];
